//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<bool> IsTransportAvailable { get; set; }
        public Nullable<System.DateTime> BookDate { get; set; }
        public Nullable<int> ConsignmentId { get; set; }
        public Nullable<decimal> Tonnage { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string CargoLocation { get; set; }
        public Nullable<int> ItemCount { get; set; }
        public string ItemType { get; set; }
        public string CargoDestination { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    }
}
