//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consignment
    {
        public int Id { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ManifestId { get; set; }
        public string ConsignmentRef { get; set; }
        public string BillOfLaden { get; set; }
        public string Name { get; set; }
        public string Shipper { get; set; }
        public Nullable<System.DateTime> SailedDate { get; set; }
        public string Description { get; set; }
        public string WeightUnit { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> PackageUnit { get; set; }
        public string PackageType { get; set; }
        public string Address { get; set; }
        public string Telephones { get; set; }
        public string Email { get; set; }
        public string NothifyName { get; set; }
        public string NotifyAddress { get; set; }
        public string NotifyTelephone { get; set; }
        public string NotifyEmail { get; set; }
        public string OtherInfo { get; set; }
        public string NothifyOtherInfo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string MarksSeals { get; set; }
        public string Remarks { get; set; }
    }
}
