//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyPlantRequest
    {
        public int Id { get; set; }
        public Nullable<int> LoadingPlanId { get; set; }
        public Nullable<int> StorageBillId { get; set; }
        public string RequestRef { get; set; }
        public string Zone { get; set; }
        public string Vessel { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string ReceiptNumber { get; set; }
        public string DebitNoteNumber { get; set; }
        public string PlantType { get; set; }
        public Nullable<int> PlantQty { get; set; }
        public Nullable<int> ResponseQty { get; set; }
        public string ResponseRemark { get; set; }
        public string ResponseUser { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public Nullable<decimal> PlantTonnage { get; set; }
        public string Location { get; set; }
        public string ForkLiftDriverName { get; set; }
        public string RequestedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string Remark { get; set; }
    }
}
