//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destination
    {
        public int Id { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public string CreaedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
