//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreightRate
    {
        public int Id { get; set; }
        public string FreightRef { get; set; }
        public Nullable<int> DestinationId { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string IsUsed { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string FreightRateKey { get; set; }
    }
}
