//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EnlLogistiicsEntities : DbContext
    {
        public EnlLogistiicsEntities()
            : base("name=EnlLogistiicsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<BookingMachinery> BookingMachineries { get; set; }
        public virtual DbSet<Cargo_Location> Cargo_Location { get; set; }
        public virtual DbSet<CargoDestination> CargoDestinations { get; set; }
        public virtual DbSet<Consignment> Consignments { get; set; }
        public virtual DbSet<ConsignmentEvacuation> ConsignmentEvacuations { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DailyPlantRequest> DailyPlantRequests { get; set; }
        public virtual DbSet<Destination> Destinations { get; set; }
        public virtual DbSet<Equipments_Rate> Equipments_Rate { get; set; }
        public virtual DbSet<FreightRate> FreightRates { get; set; }
        public virtual DbSet<Handling_Equipment> Handling_Equipment { get; set; }
        public virtual DbSet<ItemApproval> ItemApprovals { get; set; }
        public virtual DbSet<LoadingPlan> LoadingPlans { get; set; }
        public virtual DbSet<Machine_Status> Machine_Status { get; set; }
        public virtual DbSet<Machinery_Registration> Machinery_Registration { get; set; }
        public virtual DbSet<Manifest> Manifests { get; set; }
        public virtual DbSet<PersonTitle> PersonTitles { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<QuoteRequest> QuoteRequests { get; set; }
        public virtual DbSet<SalesOrder> SalesOrders { get; set; }
        public virtual DbSet<Service_Request> Service_Request { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<StorageBill> StorageBills { get; set; }
        public virtual DbSet<StorageBillStatu> StorageBillStatus { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Transport_Equipment> Transport_Equipment { get; set; }
        public virtual DbSet<TruckBatch> TruckBatches { get; set; }
        public virtual DbSet<TruckRequest> TruckRequests { get; set; }
        public virtual DbSet<Vehicle_Category> Vehicle_Category { get; set; }
        public virtual DbSet<Vehicle_Make> Vehicle_Make { get; set; }
        public virtual DbSet<Vehicle_Manufacturer> Vehicle_Manufacturer { get; set; }
        public virtual DbSet<Vehicle_Model> Vehicle_Model { get; set; }
        public virtual DbSet<Vehicle_Owner> Vehicle_Owner { get; set; }
        public virtual DbSet<Vehicle_Owner_Driver> Vehicle_Owner_Driver { get; set; }
        public virtual DbSet<Vehicle_Registration> Vehicle_Registration { get; set; }
        public virtual DbSet<VehiclesOnQueue> VehiclesOnQueues { get; set; }
        public virtual DbSet<VepMonitoring> VepMonitorings { get; set; }
        public virtual DbSet<MailSetting> MailSettings { get; set; }
        public virtual DbSet<VechicleCallUpRequest> VechicleCallUpRequests { get; set; }
        public virtual DbSet<LoadingPlanTransporter> LoadingPlanTransporters { get; set; }
        public virtual DbSet<TruckCallup> TruckCallups { get; set; }
        public virtual DbSet<OtherVehicleDetail> OtherVehicleDetails { get; set; }
        public virtual DbSet<VehicleEntryPermit> VehicleEntryPermits { get; set; }
    
        public virtual ObjectResult<SP_GetPlantRequestWithPlantCount_Result> SP_GetPlantRequestWithPlantCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetPlantRequestWithPlantCount_Result>("SP_GetPlantRequestWithPlantCount");
        }
    
        public virtual ObjectResult<SP1_GetPlantRequestWithPlantCount_Result> SP1_GetPlantRequestWithPlantCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP1_GetPlantRequestWithPlantCount_Result>("SP1_GetPlantRequestWithPlantCount");
        }
    }
}
