//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadingPlan
    {
        public int Id { get; set; }
        public Nullable<int> IdC { get; set; }
        public string PlanRef { get; set; }
        public Nullable<int> StorageBillId { get; set; }
        public Nullable<int> BatchNumber { get; set; }
        public Nullable<int> TruckQty { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public string DestinationDes { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
