//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machinery_Registration
    {
        public int Id { get; set; }
        public string MachineRef { get; set; }
        public string AssetId { get; set; }
        public string AssetName { get; set; }
        public string AssetModel { get; set; }
        public string AssetWheels { get; set; }
        public string AssetDescription { get; set; }
        public string CapacityUnity { get; set; }
        public Nullable<decimal> HandlingCapacity { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsRated { get; set; }
    }
}
