//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manifest
    {
        public int Id { get; set; }
        public string ManifestRef { get; set; }
        public Nullable<System.DateTime> ManifestDate { get; set; }
        public string RotationNumber { get; set; }
        public Nullable<System.DateTime> DateOfReport { get; set; }
        public string Area { get; set; }
        public string Port { get; set; }
        public string ShipNameNumber { get; set; }
        public Nullable<decimal> RegTonnage { get; set; }
        public string CountryOfRegister { get; set; }
        public string NameOfMaster { get; set; }
        public Nullable<int> NoOfCrew { get; set; }
        public string PlaceFromArraival { get; set; }
        public string NoOfBl { get; set; }
        public string Description { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    }
}
