//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public int Id { get; set; }
        public string PurchaseOrderRef { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public string Created_by { get; set; }
    }
}
