//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteRequest
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> ServiceRequestId { get; set; }
        public Nullable<int> ServiceCodeId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Service_Request Service_Request { get; set; }
    }
}
