//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageBill
    {
        public int Id { get; set; }
        public string StorageBillRef { get; set; }
        public Nullable<System.DateTime> DateOnBill { get; set; }
        public string LogSheetNo { get; set; }
        public string RbNumber { get; set; }
        public string BillOfLaden { get; set; }
        public string DeliveryOrderNumber { get; set; }
        public string ClearingAgent { get; set; }
        public string VoyageNumber { get; set; }
        public string VesselName { get; set; }
        public Nullable<System.DateTime> DischargeDate { get; set; }
        public string RentExemption { get; set; }
        public Nullable<decimal> CubicMeasure { get; set; }
        public string IsAuth { get; set; }
        public string IsLoadPlan { get; set; }
        public Nullable<System.DateTime> RentFrom { get; set; }
        public Nullable<System.DateTime> RentTo { get; set; }
        public Nullable<int> TotalDays { get; set; }
        public string DaysDischargable { get; set; }
        public string ShippingAgent { get; set; }
        public string ConsigneeName { get; set; }
        public string ConsigneeAddress { get; set; }
        public string CargoClass { get; set; }
        public string Description { get; set; }
        public string MarksNumber { get; set; }
        public string Units { get; set; }
        public Nullable<decimal> Tones { get; set; }
        public string ReceiptNumber { get; set; }
        public string IsWorchop { get; set; }
        public Nullable<int> IssuedVeps { get; set; }
        public Nullable<bool> VepConfirmed { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
