//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport_Equipment
    {
        public int Id { get; set; }
        public string Ref { get; set; }
        public Nullable<int> Assetid { get; set; }
        public Nullable<int> Ownerid { get; set; }
        public Nullable<int> Registrationid { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreatedBy { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Availability { get; set; }
        public string Location { get; set; }
    }
}
