//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckRequest
    {
        public int Id { get; set; }
        public Nullable<int> StorageBillId { get; set; }
        public string RequestRef { get; set; }
        public string Vessels { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> Serial { get; set; }
        public string Zone { get; set; }
        public string BatchShift { get; set; }
        public Nullable<int> TotalTruck { get; set; }
        public string IsAuth { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
    }
}
