//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiclesOnQueue
    {
        public int Id { get; set; }
        public string QueueRef { get; set; }
        public string QueueKey { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public string VehicleNo { get; set; }
        public string VehicleRef { get; set; }
        public Nullable<System.DateTime> DateTimeIn { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
