//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleEntryPermit
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> VepDate { get; set; }
        public string VepRef { get; set; }
        public Nullable<int> StorageBillId { get; set; }
        public string RecNumber { get; set; }
        public string RbNumber { get; set; }
        public string RotationNumber { get; set; }
        public string LocationOfCargo { get; set; }
        public string AuthorizedPerson { get; set; }
        public string VehicleNo { get; set; }
        public string DriverName { get; set; }
        public string DriverLicenceNo { get; set; }
        public Nullable<System.DateTime> LicenceExpDate { get; set; }
        public string QtyTypeOfCargo { get; set; }
        public Nullable<decimal> Tonnage { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
