//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle_Owner
    {
        public int Id { get; set; }
        public string OwnerRef { get; set; }
        public string Name { get; set; }
        public string ContactAddress { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Email { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string AddedBy { get; set; }
    
        public virtual Vehicle_Owner_Driver Vehicle_Owner_Driver { get; set; }
    }
}
