//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle_Owner_Driver
    {
        public int Id { get; set; }
        public Nullable<int> v_driver_title { get; set; }
        public string v_driver_fname { get; set; }
        public string v_driver_oname { get; set; }
        public Nullable<int> v_id { get; set; }
        public Nullable<int> v_owner_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public string created_by { get; set; }
    
        public virtual Vehicle_Owner Vehicle_Owner { get; set; }
    }
}
